### ISSUE TITLE
ConstantItemFilter throws on testing against an empty stack, and no other ItemFilter does

### ISSUE THREAD

**Issue by LemmaEOF** [AlexIIL/LibBlockAttributes#12]
[`ConstantItemFilter`](https://github.com/AlexIIL/LibBlockAttributes/blob/0.4.x-1.14.x/src/main/java/alexiil/mc/lib/attributes/item/filter/ConstantItemFilter.java#L29) has a throw when the passed ItemStack is empty. This would be all fine and good, since the javadocs for ItemFilter say to do this, *but* no other built-in item filter follows this behavior. I don't think that throwing when testing an empty stack like this is a good idea, but whether it really should or not, it should be consistent across *all* built-in filters to avoid confusion.

**Comment by AlexIIL** [comment]
I changed this behaviour a while ago and forgot to comment, woops.
