### ISSUE TITLE
FluidKeys$VoidWorldView constructor crashes dedicated servers

### ISSUE THREAD

**Issue by Linguardium** [AlexIIL/LibBlockAttributes#22]
Saw this issue with mechanized when placing the boiler. Server hard crashes with "method not found" when referencing getDimensionTypeRegistry() which is a client only method.

https://github.com/AlexIIL/LibBlockAttributes/blob/a0cea30f86c05f2b0c4e6f98d48d10ef0bcf366f/src/main/java/alexiil/mc/lib/attributes/fluid/volume/FluidKeys.java#L252

**Comment by Linguardium** [comment]
crashlog here: https://hastebin.com/ahisitiqir.rb

**Comment by AlexIIL** [comment]
Ok, this should be fixed in `0.7.1-pre.4` (currently only on the buildcraft maven, but I'll release it properly soon).

**Comment by Linguardium** [comment]
just tested, seems to function :)  Thanks for the quick response

**Comment by AlexIIL** [comment]
I should have closed this a while ago, sorry :/
