### ISSUE TITLE
No way to get an actual Fluid from a FluidVolume

### ISSUE THREAD

**Issue by LemmaEOF** [AlexIIL/LibBlockAttributes#4]
I'm trying to get a `Fluid` from an abstract FluidVolume, but it doesn't seem to be possible at all. You can only get the FluidKey, and I can't find any way to  convert from an abstract FluidKey to a Fluid. I think having an abstract FluidVolume in the first place is inherently counterproductive; it makes interaction between even vanilla and modded nearly unintelligible, since you don't know what *type* of FluidVolume you're dealing with, which is a massive roadblock to doing anything else. I honestly think it'd be an infinitely better experience to add the merge/split code into the Silk FluidInstance and use those instead.

**Comment by AlexIIL** [comment]
```java
FluidVolume volume = ...
if (volume instanceof NormalFluidVolume) {
    Fluid minecraftFluid = ((NormalFluidVolume) volume).getRawFluid();
} else if (volume instanceof PotionFluidVolume) {
    Potion minecraftPotion = ((PotionFluidVolume) volume).getPotion();
} else {
    // We don't know
}
```

**Comment by AlexIIL** [comment]
Although I can add a `getRawFluid()` method to `FluidVolume` and `FluidKey` and just let them return null for things based on stuff other than fluids?

**Comment by AlexIIL** [comment]
Ok I've added some utility/helper methods in [0.3.4](https://github.com/AlexIIL/LibBlockAttributes/blob/0.3.x-1.14.x/src/main/resources/changelog/0.3.4.txt) and I've updated the [fluids](https://github.com/AlexIIL/LibBlockAttributes/wiki/Fluids) and [fluid inventory](https://github.com/AlexIIL/LibBlockAttributes/wiki/Fluid-Inv-Management) wiki pages a bit.

**Comment by LemmaEOF** [comment]
I'm satisfied with how it's set up.
