### ISSUE TITLE
Powering dropper that pointing any inventory that using this lib will killing the world

### ISSUE THREAD

**Issue by panbanann** [AlexIIL/LibBlockAttributes#40]
As in title simple Redstone contraption with dropper powered by button, pointing any inventory which is using your lib, will crash the single-player game and server.

[https://pastebin.com/TuwkxbGn](https://pastebin.com/TuwkxbGn)

**Comment by AlexIIL** [comment]
I think this is a duplicate of #34, and so can be fixed by manually updating LBA to [0.8.5](https://alexiil.uk/maven/alexiil/mc/lib/libblockattributes-all/0.8.5/libblockattributes-all-0.8.5.jar)?

**Comment by panbanann** [comment]
It works! Thank you! sorry for the duplicate and problem.

**Comment by AlexIIL** [comment]
OK :)
