### ISSUE TITLE
BlockView support for mods depending on this library

### ISSUE THREAD

**Issue by ghost** [AlexIIL/LibBlockAttributes#42]
Hello, just wondering if you're able to change Attribute#getAll to use the BlockView interface instead of the World class, would allow to use child instances of BlockView in methods that don't provide a world instance. (World class implements BlockView, and you're using the methods that BlockView provides, so wouldn't have to change anything else)

**Comment by AlexIIL** [comment]
That's not really possible, since the `World` object is passed down through a lot more code than just `Attribute.getAll`, plus it ends up outside LBA code in the mods that actually provide attributes.

(The main problem is that I'd have to break LBA's APIs in order to make this work).

**Comment by AlexIIL** [comment]
When would you need to use this? Do you need to grab attributes when you only have a `WorldView`

**Comment by AlexIIL** [comment]
*(Woops, sorry for the miss-click closing).*

What are you trying to do? LBA is a fairly general-purpose library, so there's no guarantee that attribute instances support just a `BlockView`. However there might be an alternative depending on what you need...

**Comment by ghost** [comment]
For the first reply, understandable, not much i can add onto that. For the second/third reply, yes i do need to grab attributes in a method that only provides a WorldView instance. Trying to set an attribute on the server, and then retrieve in a client, but that client method only provide the WorldView instance.

**Comment by AlexIIL** [comment]
> Trying to set an attribute on the server, and then retrieve in a client

Sadly LBA doesn't provide that functionality - LBA can only retrieve objects on the same side as where they are provided.

**Comment by AlexIIL** [comment]
What kind of object are you setting/retrieving?

**Comment by ghost** [comment]
> 
> 
> What kind of object are you setting/retrieving?

A custom attribute class, also do you have discord? (mines chaottic#3842) to chat on that instead of in this lol

**Comment by AlexIIL** [comment]
> discord

Yes, https://discord.gg/BjnuMUs

**Comment by AlexIIL** [comment]
*(Closing after discussion has long since finished).*
