### ISSUE TITLE
Crash with hopper transfer

### ISSUE THREAD

**Issue by Juuxel** [AlexIIL/LibBlockAttributes#5]
Full log: https://gist.github.com/Juuxel/f45bde9f7f85766c8a24238fa97bf2d4  
Full mod source: https://github.com/Juuxel/Adorn/tree/c034f0bdf49859f5bf9b1e42625aea3caabe8701

Transferring items into a `SimpleFixedItemInv` through a `PartialInventoryFixedWrapper` (custom subclass, [link](https://github.com/Juuxel/Adorn/blob/c034f0bdf49859f5bf9b1e42625aea3caabe8701/src/main/kotlin/juuxel/adorn/util/SidedFixedInventoryWrapper.kt)) crashes the game with an `IllegalStateException`.

It seems that hoppers modify the stored stacks in HopperBlockEntity.transfer:
![](https://cdn.discordapp.com/attachments/561268356481548294/570252718963294210/unknown.png)

**Comment by LemmaEOF** [comment]
I think trying to treat inv stacks in a FixedItemInv as immutable is a *very* bad idea. Mojang has made it very clear that mutable ItemStacks are the way to go, and LBA should follow that.

**Comment by AlexIIL** [comment]
This should be fixed properly in 0.4.1 or 0.4.2 - I'm not sure which one fixed it properly, but either way it works correctly now.

@Boundarybreaker That really belongs is a separate issue, although I guess we're talking about it in the lba discord channel so we might not need to.
