### ISSUE TITLE
[Fabric 1.14 | 0.4.0]

### ISSUE THREAD

**Issue by Diamondman121314** [AlexIIL/LibBlockAttributes#6]
When trying to interact with the tank at all, such as clicking on it, or even just placing a pipe next to it (as I specifically clicked on the ground to place the pipe), it crashes the game. I do have a [crash report](https://gist.github.com/Diamondman121314/68444669d928afa7e7981b05cd1fd284).

**Comment by AlexIIL** [comment]
*Technically* this is SimplePipe's fault (see https://github.com/AlexIIL/SimplePipes/issues/13), but as I made both it's still my fault :p

(Although I'll track this in simple pipes' issue tracker).
